#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 4005afce-b9c2-4864-9d77-49d52912d772
# Source File: ..\..\..\..\Users\tipr_admin\Documents\SAPIEN\Projects\Blog - Event Handlers\Event Handlers.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
BwIAAB+LCAAAAAAABACNkVtPwyAYhu+X7D8Q7jvapnM2oVy4g3rhIXPx1rD2q8FQaIAu7t9LLTVd
TIx3PPDyvOGD7qHUJzDnDXeczWcI0WejP6B03+DxFYwVWrFkkVAyQjjbCQn3G5bF8ZLXJUTHvEyj
7Poqi/JqtYqyvFqmeZL6dUpJCIeroeVwboHFlExxlGtZ+TpEpm02QEC0hxoMqBIeeQMFxuimE7Iq
cIzZi+PGde2itXYo//vqmksZPXChdto0b62tp65x38vqf8tupT5y6VXJRIXWumm4qrafDlQ/ywIf
TAeYDWnrG5KLhgGGd//MaaAnI96F4rIP9L1sewLl0J3XSz85r2p9nJJfufmMkouP/wJlTsElBwIA
AA==#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2015 v4.2.99
     Generated on:       31-12-2015 13:38
     Generated by:        
     Organization:        
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2015
#>


#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
SwQAAB+LCAAAAAAABAC9lEtLAzEQgO+C/yH0vOzD7boWsgtS6UXQ4kr1mk1nS2geZZK07L93W0sV
PYiFhlwyEzIfH8MMfQFutoD9A3OMDBcrjK5GN6P6+ooQ+oxiJTSTMyHhiSmoG8fQ+U28sZYmv14P
f+6tBdVKAfYQf2X6WlluUIo2IosjaRyn+xORqZfOI1QavEMmIzL3Qw3+CP2rWYOu2rJkBS9us0k+
hvRuQpNT1Z+UprcOVAhG/Cb00uxsPDOobBDivk9hQMh2Qq/OYaV5V3Rll2XLImU5+5v1rmQYJ4HA
ncG+AdwKDme17N92U4MQRO9oNUczqF3A7RR+zjZNvi+P+gNBqg7+SwQAAA==#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Call-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$global:ExitCode = 0 #Set the exit code for the Packager
}






#endregion Source: Startup.pss

#region Source: MainForm.psf
function Call-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
igsAAB+LCAAAAAAABAC9Vl2PmkAUfW/S/0DnmYig6JogSWW7SVPbmmK3fdsMeLVThxkzM6xLf30H
Abt+VXRXY2IcOJdzzz3nGrxvEPNHENktVtjQPyThrI8c5L99YxjeV0FmhGF6Ryh8wQn4nzFhd1wk
jYWcetbO7aIo+g2xMlS2gD4KM6kgafwgbMKXspHXFt+mse+WadyXPbQbzfxjGkFKVSqgzyBVAlPT
GKURJfEnyMZ8DqwfdbvYjd2O3Wu1oXnTQwbTrfRR1Soy4l+EToSGooAzJTiVhTzd60jwBQiVlTUB
JcBUSP4A8p2eYxq20/asCnSgKFeO1pM5Cg8VFmrEJVFaJvIDTQgijAUAO1o7hieF/Fu+ZJTjCYjd
gg+P+nkleqgx/xp7yI+etQJU6ONWDVKlOLu4WdGKphL2P8t2hzLkMS5m6djasptdxw55tslao6xI
RqdjGk6rBnyMo49sAk/Ir4XeMPddjYrvEu6JTDENVUZhgON5wCkXyB+LFPbVP0+Hzno8357Bw+rq
VkqsIib1Q6OJZwKkHGBx8eQsSq4Ii5fGJ0/Pnn0/lJ49zLUj5JyRIWd32092ZogjoBf3hOYsVQhe
4obbrO3GBucJPrj6T75zkg927V0+2M6GcZuH91JCoqcMssKWVzI/kTEXlESv4JRnrZ+6zVJk4xoc
r56/44z5a851iAReEjY7h6vZmrrT7tS2J24Tt/Bxrp8JvY4mInRMuchCEI8khrMsO1ldwAVcRV6p
Sq+qlnYBbetjsdue9fzd2/8LRTe59IoLAAA=#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$MainForm = New-Object 'System.Windows.Forms.Form'
	$buttonDownload = New-Object 'System.Windows.Forms.Button'
	$progressbarDownload = New-Object 'System.Windows.Forms.ProgressBar'
	$labelProgress = New-Object 'System.Windows.Forms.Label'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	$MainForm_Load = {
	    $script:webclient = New-Object -TypeName System.Net.WebClient
	    $webclient.add_DownloadProgressChanged($webclient_DownloadProgressChanged)
	    $webclient.add_DownloadFileCompleted($webclient_DownloadFileCompleted)
	}
	
	$webclient_DownloadProgressChanged = {
	    $progressInfo = $_
	    $progressbarDownload.Value = $progressInfo.ProgressPercentage
	    $labelProgress.Text = "$($progressInfo.BytesReceived) bytes received of $($progressInfo.TotalBytesToReceive)"
	}
	
	$webclient_DownloadFileCompleted = {
	    $labelProgress.Text = 'Download complete'
	}
	
	$buttonDownload_Click = {
	    $webclient.DownloadFileAsync('http://go.microsoft.com/fwlink/?LinkID=87342&clcid=0x409', 'd:\temp\mpam-fe.exe')
	}
	
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$MainForm.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonDownload.remove_Click($buttonDownload_Click)
			$MainForm.remove_Load($MainForm_Load)
			$MainForm.remove_Load($Form_StateCorrection_Load)
			$MainForm.remove_Closing($Form_StoreValues_Closing)
			$MainForm.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$MainForm.SuspendLayout()
	#
	# MainForm
	#
	$MainForm.Controls.Add($buttonDownload)
	$MainForm.Controls.Add($progressbarDownload)
	$MainForm.Controls.Add($labelProgress)
	$MainForm.ClientSize = '292, 124'
	$MainForm.Name = 'MainForm'
	$MainForm.StartPosition = 'CenterScreen'
	$MainForm.Text = 'Downloader'
	$MainForm.add_Load($MainForm_Load)
	#
	# buttonDownload
	#
	$buttonDownload.Location = '212, 84'
	$buttonDownload.Name = 'buttonDownload'
	$buttonDownload.Size = '66, 23'
	$buttonDownload.TabIndex = 3
	$buttonDownload.Text = 'Download!'
	$buttonDownload.UseVisualStyleBackColor = $True
	$buttonDownload.add_Click($buttonDownload_Click)
	#
	# progressbarDownload
	#
	$progressbarDownload.Location = '12, 24'
	$progressbarDownload.Name = 'progressbarDownload'
	$progressbarDownload.Size = '266, 23'
	$progressbarDownload.TabIndex = 2
	#
	# labelProgress
	#
	$labelProgress.Location = '12, 50'
	$labelProgress.Name = 'labelProgress'
	$labelProgress.Size = '265, 16'
	$labelProgress.TabIndex = 1
	$labelProgress.Text = 'Progress'
	$MainForm.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $MainForm.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$MainForm.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$MainForm.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$MainForm.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $MainForm.ShowDialog()

}
#endregion Source: MainForm.psf

#region Source: Globals.ps1
	#endregion Source: Globals.ps1

#Start the application
Main ($CommandLine)
